-   name: Setup bash profile
    become: yes
    become_user: "{{ user }}"
    lineinfile: dest="/home/{{ user }}/.bash_profile"
                create=yes
                regexp="{{ item.reg }}"
                line="{{ item.line }}"
    with_items:
        - { reg: 'export SYMFONY_ENV=', line: "export SYMFONY_ENV={{ enviroment }}"}
        - { reg: 'cd {{ doc_root }}/../', line: 'cd {{ doc_root }}/../'}
        - { reg: 'export PATH=$HOME/.config/composer/vendor/bin/:$PATH', line: 'export PATH=$HOME/.config/composer/vendor/bin/:$PATH' }

-   name: Change bash up and down arrow function
    become: yes
    become_user: "{{ user }}"
    lineinfile: dest="/home/{{ user }}/.inputrc"
                create=yes
                regexp="{{ item.reg }}"
                line="{{ item.line }}"
    with_items:
        - { reg: '\"\\e\[A\":history-search-backward', line: '\"\\e[A\":history-search-backward' }
        - { reg: '\"\\e\[B\":history-search-forward', line: '\"\\e[B\":history-search-forward' }
